### ISSUE TITLE
The DENSE web server is not functioning properly.

### ISSUE THREAD

**Issue by Galaxy-228** [i2bc/dense#1]
Hi,
Thank you for developing the DENSE software.
When i submit the the info of TRGs to the DENSE web server (https://bioi2.i2bc.paris-saclay.fr/django/denovodb/dense-
run/), the program does not seem to be running properly. May I ask if you have already deployed it?

Best,
Jie

**Comment by ChloeQuignot** [comment]
Hi,

Thanks for using DENSE. We've already exchanged by email but here's a quick summary for the records:

The dense web server is unfortunately limited in upload size. By experience, a total size of 1Gb of data is already quite large and slows down the upload considerably, we've adjusted the help messages on the web server to make this clearer. I would advise anyone with large datasets to run DENSE via command line instead. 

If you need any help on using DENSE via command line, don't hesitate to create an issue in this GitHub project.
For any questions about the web server specifically, please prefer to contact the BIOI2 platform at contact-bioi2@i2bc.paris-saclay.fr.

Thanks for your understanding,
Chloe
